[package]
name = "matrix"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "matrix"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.29.1"
lazy_static = "1.4.0"
image = { version = "0.24.7", default-features = false, features = ["gif", "jpeg", "png"] }
